### ISSUE TITLE
Arg descriptions can contain HTML

### ISSUE THREAD

**Issue by roborourke** [humanmade/Restsplain#12]
Some of the jetpack endpoints contain arg descriptions with HTML. Legit or no there are 2 things it might be good to do here:

1. Use `MaybeHTML` component for descriptions
2. Update `MaybeHTML` HTML regex to detect `&#?[^;]+;` patterns

**Comment by rmccue** [comment]
Yeah... they shouldn't do that.

**Comment by roborourke** [comment]
Heh. So won't fix!
